// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/add-offer": {
            "post": {
                "description": "Add a new offer by passing in the whole offer details including offer validity date",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OFFERS"
                ],
                "summary": "Add A new Offer for an existing Country",
                "parameters": [
                    {
                        "description": "Add a new offer",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.AddNewOffer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/get-offer/{country}": {
            "get": {
                "description": "Get Latest Offer from different Countries by passing country short form",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OFFERS"
                ],
                "summary": "Get Offer Based On Country",
                "parameters": [
                    {
                        "type": "string",
                        "description": "country short form",
                        "name": "country",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AddNewOffer": {
            "type": "object",
            "properties": {
                "clientId": {
                    "type": "integer"
                },
                "country": {
                    "type": "string"
                },
                "flag": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "imageHeight": {
                    "type": "integer"
                },
                "imageWidth": {
                    "type": "integer"
                },
                "offerHome": {
                    "type": "integer"
                },
                "pageCount": {
                    "type": "integer"
                },
                "position": {
                    "type": "integer"
                },
                "showFrom": {
                    "type": "string"
                },
                "storeURL": {
                    "type": "string"
                },
                "storeURLTitle": {
                    "type": "string"
                },
                "textLocale": {
                    "type": "string"
                },
                "validFrom": {
                    "type": "string"
                },
                "validTo": {
                    "type": "string"
                },
                "validityTextLocale": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {},
                "message": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "abhinandkakkadi.com",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
